name: Build & Publish Wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request: {}
  push:
    tags:
      - 'v*'

jobs:
  seed-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - run: |
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then
            PLATFORM="linux/amd64"
            LIBDIR="x86_64-linux-gnu"
          else
            PLATFORM="linux/arm64"
            LIBDIR="aarch64-linux-gnu"
          fi
          OUT_DIR="camera_reader/_vendor/linux_$ARCH"
          mkdir -p "$OUT_DIR"
          docker run --rm --platform "$PLATFORM" \
            -v "$(pwd)/$OUT_DIR":/vendor ubuntu:22.04 bash -c "\
              apt-get update && \
              apt-get install -y libaravis-0.8-0 gir1.2-aravis-0.8 && \
              cp /usr/lib/${LIBDIR}/libaravis-0.8.so* /vendor/ && \
              cp /usr/lib/${LIBDIR}/girepository-1.0/Aravis-0.8.typelib /vendor/"
      - uses: actions/upload-artifact@v4
        with:
          name: vendor-linux
          path: camera_reader/_vendor/linux_*

  seed-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /Users/runner/Library/Caches/Homebrew
          key: ${{ runner.os }}-homebrew-cache
      - run: |
          brew update
          brew install aravis pygobject3 || true
          for arch in x86_64 arm64; do
            out=./camera_reader/_vendor/macosx_${arch}
            mkdir -p "$out"
            cp "$(brew --prefix)/lib/libaravis-0.8.dylib" "$out/"
            cp "$(brew --prefix)/lib/girepository-1.0/Aravis-0.8.typelib" "$out/"
          done
      - uses: actions/upload-artifact@v4
        with:
          name: vendor-macos
          path: camera_reader/_vendor/macosx_*

  seed-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
      - run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm mingw-w64-x86_64-aravis mingw-w64-x86_64-gobject-introspection
          mkdir -p camera_reader/_vendor/win_amd64
          cp /mingw64/bin/libaravis-0.8-0.dll camera_reader/_vendor/win_amd64/
          cp /mingw64/lib/girepository-1.0/Aravis-0.8.typelib camera_reader/_vendor/win_amd64/
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: false
      - run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm mingw-w64-clang-aarch64-aravis mingw-w64-clang-aarch64-gobject-introspection
          mkdir -p camera_reader/_vendor/win_arm64
          cp /clangarm64/bin/libaravis-0.8-0.dll camera_reader/_vendor/win_arm64/
          cp /clangarm64/lib/girepository-1.0/Aravis-0.8.typelib camera_reader/_vendor/win_arm64/
      - uses: actions/upload-artifact@v4
        with:
          name: vendor-windows
          path: camera_reader/_vendor/win_*

  build-wheels:
    needs: [seed-linux, seed-macos, seed-windows]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: vendor-artifacts
      - run: |
          mkdir -p camera_reader/_vendor
          find vendor-artifacts -type d -path "*/camera_reader/_vendor/*" -exec cp -r {} camera_reader/_vendor/ \;
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - run: |
          ver="${{ matrix.python-version }}"
          ver_nodot="${ver//./}"
          echo "CIBW_BUILD=cp${ver_nodot}-*" >> $GITHUB_ENV
          echo "CIBW_ARCHS=x86_64 aarch64" >> $GITHUB_ENV
          echo "CIBW_ENVIRONMENT_MACOS=MACOSX_DEPLOYMENT_TARGET=15.0" >> $GITHUB_ENV
          echo "CIBW_REPAIR_WHEEL_COMMAND=bash -c 'mkdir -p {wheel}/camera_reader/_vendor && cp -r camera_reader/_vendor/* {wheel}/camera_reader/_vendor/'" >> $GITHUB_ENV
          echo "CIBW_REPAIR_WHEEL_COMMAND_WINDOWS=powershell -Command \"mkdir (Resolve-Path \$env:WHEEL)\\camera_reader\\_vendor -ea 0; Copy-Item -Recurse camera_reader\\_vendor\\* (Resolve-Path \$env:WHEEL)\\camera_reader\\_vendor\"" >> $GITHUB_ENV
      - run: python -m pip install --upgrade cibuildwheel==2.23.3
      - uses: pypa/cibuildwheel@v2.23.3
        with:
          output-dir: wheelhouse
      - if: runner.os == 'Linux'
        run: |
          python -m pip install auditwheel
          mkdir -p repaired
          for whl in wheelhouse/*.whl; do
            if [[ "$whl" == *x86_64*.whl ]]; then
              auditwheel repair "$whl" -w repaired/
            else
              cp "$whl" repaired/
            fi
          done
      - if: runner.os == 'macOS'
        run: |
          python -m pip install delocate-wheel
          mkdir -p repaired
          delocate-wheel -w repaired wheelhouse/*.whl
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.python-version }}
          path: repaired/*.whl

  publish:
    needs: build-wheels
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v1
        with:
          files: '**/*.whl'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
